name: CI Tests

on: [push, pull_request, pull_request_target]

jobs:
  cairo-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Cairo
        run: make install
      - name: Run tests
        run: make test
